
[workspace]
members = [
    "packages/combat",
    "packages/beast",
]

[package]
name = "death_mountain"
version.workspace = true
keywords.workspace = true
edition.workspace = true

[workspace.package]
version = "1.0.0"
edition = "2024_07"
cairo-version = "2.13.1"
scarb-version = "2.13.1"
authors = ["Provable Games"]
description = "Death Mountain Components"
documentation = "https://docs.provable.games/lootsurvivor"
repository = "https://github.com/Provable-Games/death-mountain"
license-file = "licenses/BUSL_LICENSE"
keywords = [
    "death_mountain",
    "starknet",
]

[workspace.dependencies]
assert_macros = "2.13.1"
starknet = "2.13.1"
snforge_std = "0.52.0"

[dependencies]
starknet.workspace = true
death_mountain_combat = { path = "packages/combat" }
death_mountain_beast = { path = "packages/beast" }

[dev-dependencies]
snforge_std.workspace = true

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false

[workspace.tool.fmt]
max-line-length = 120
sort-module-level-items = true

[workspace.tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[tool]
fmt.workspace = true
scarb.workspace = true